Add counter examples in Solidity and Rust
oasislabs/oasis-box pull request #1
Opened 2018-11-11 01:04 UTC by armaniferrante

2018-11-11 11:48 UTC, daviddao requested changes

2018-11-11 11:48 UTC, daviddao commented on test/test-counters.js
> +const ConfidentialWasmCounter = artifacts.requir("ConfidentialWasmCounter");
Small typo: `artifacts.requir` => `artifacts.require()`

2018-11-11 20:00 UTC, armaniferrante commented on test/test-counters.js
> +const ConfidentialWasmCounter = artifacts.requir("ConfidentialWasmCounter");
Thanks :) 

Waiting for us to publish the latest owasm-abi-derive on crates.io before coming back to this.

2018-11-12 05:57 UTC, armaniferrante commented on test/test-counters.js
> +const ConfidentialWasmCounter = artifacts.requir("ConfidentialWasmCounter");
Fixed

2018-11-12 06:14 UTC, vishwa-raman approved these changes
Tested against devnet using the latest c-k image. It works! Here are the results -

Post `truffle migrate --network oasis`
```
Summary
=======
> Total deployments:   7
> Final cost:          0.03414514 ETH
```

Post `truffle test --network oasis`
```
  Contract: Counter Contracts
    ✓ should have a starting count of 0 (261ms)
    ✓ should increment the count to 1 (1140ms)
    ✓ should have a starting count of 0 (62ms)
    ✓ should increment the count to 1 (870ms)
    ✓ should have a starting count of 0 (607ms)
    ✓ should increment the count to 1 (1024ms)
    ✓ should have a starting count of 0 (106ms)
    ✓ should increment the count to 1 (967ms)
    ✓ should have a starting count of 0 (98ms)
    ✓ should increment the count to 1 (928ms)
    ✓ should have a starting count of 0 (597ms)
    ✓ should increment the count to 1 (1304ms)


  12 passing (10s)
```

Approved!

2018-11-12 06:40 UTC, merged